version: 2
updates:
  - package-ecosystem: "npm" # package manager
    directory: "/" # location of package manifests
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    groups:
      all-dependencies:
        patterns:
          - "*"
        group-name: "All dependencies"